In [26]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import shap
from matplotlib import pyplot as plt
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from pathlib import Path
from collections import Counter
from sklearn.preprocessing import StandardScaler
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy import create_engine, func
import psycopg2
from psycopg2 import sql

In [27]:
#pip install shap

In [28]:
# SQLAlchemy create_engine('postgresql://username:password@host/db_name)
engine = create_engine('postgresql://postgres:Rice!Team04@nba-visualization-project.ctxd45yjwfgs.us-east-2.rds.amazonaws.com/nba-db')

In [29]:
# Automaps the base and reflects the engine in SQLAlchemy from the create_engine def
Base = automap_base()
Base.prepare(engine, reflect=True)

In [30]:
# query syntax: df = pd.read_sql(query.statement, connection)

## players DF from players table
players_df = pd.read_sql('SELECT * FROM players', engine)
## seasons_df from modern_season_stats table
seasons_df = pd.read_sql('SELECT * FROM modern_season_stats', engine)
## per_game_df  from per_game_stats table
per_game_df = pd.read_sql('SELECT * FROM per_game_stats', engine)

In [31]:
plt.rcParams.update({'figure.figsize': (12.0, 8.0)})
plt.rcParams.update({'font.size': 14})

In [32]:
#file_path = "20_Group_4_Final_Project/Resources/modern_season_stats_clean.csv"
#seasons_df = pd.read_csv(file_path)
seasons_df

,Year,Player,Position,Age,Team,G,GS,MP,PER,TS%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,id,AllStar
0,1980.0,Kareem Abdul-Jabbar,C,32,LAL,82,0,3143,25.3,0.639,...,696,886,371,81,280,297,216.0,2034,0,1
1,1980.0,Tom Abernethy,PF,25,GSW,67,0,1222,11.0,0.511,...,129,191,87,35,12,39,118.0,362,1,0
2,1980.0,Alvan Adams,C,25,PHO,75,0,2168,19.2,0.571,...,451,609,322,108,55,218,237.0,1118,2,0
3,1980.0,Tiny Archibald,PG,31,BOS,80,80,2864,15.3,0.574,...,138,197,671,106,10,242,218.0,1131,3,1
4,1980.0,Dennis Awtrey,C,31,CHI,26,0,560,7.4,0.524,...,86,115,40,12,15,27,66.0,86,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,2017.0,Cody Zeller,PF,24,CHO,62,58,1725,16.7,0.604,...,270,405,99,62,58,65,189.0,639,18922,0
18923,2017.0,Tyler Zeller,C,27,BOS,51,5,525,13.0,0.508,...,81,124,42,7,21,20,61.0,178,18923,0
18924,2017.0,Stephen Zimmerman,C,20,ORL,19,0,108,7.3,0.346,...,24,35,4,2,5,3,17.0,23,18924,0
18925,2017.0,Paul Zipser,SF,22,CHI,44,18,843,6.9,0.503,...,110,125,36,15,16,40,78.0,240,18925,0
18926,2017.0,Ivica Zubac,C,19,LAL,38,11,609,17.0,0.547,...,118,159,30,14,33,30,66.0,284,18926,0

In [33]:
#file_path2 = "20_Group_4_Final_Project/Resources/players_clean.csv"
#player_shape_df = pd.read_csv(file_path2)
players_df

                 Player  height  weight  born  year_start  year_end position
0       Curly Armstrong      71     170  1918         NaN       NaN     None
1          Cliff Barker      74     183  1921         NaN       NaN     None
2         Leo Barnhorst      76     190  1924         NaN       NaN     None
3            Ed Bartels      77     194  1925         NaN       NaN     None
4           Ralph Beard      70     174  1927         NaN       NaN     None
...                 ...     ...     ...   ...         ...       ...      ...
3914      Troy Williams      78     214  1969         NaN       NaN     None
3915       Kyle Wiltjer      82     238  1992      2017.0    2017.0        F
3916  Stephen Zimmerman      84     238  1996      2017.0    2017.0        C
3917        Paul Zipser      80     214  1994      2017.0    2018.0        G
3918        Ivica Zubac      85     265  1997      2017.0    2018.0        C

[3919 rows x 7 columns]

In [34]:
#file_path3 = "20_Group_4_Final_Project/Resources/per_game_stats_clean.csv"
#per_game_df = pd.read_csv(file_path3)
per_game_df

,Year,Player,Pos,MP(Game),Points(Game),Assists(Game),Rebounds(Game),Steals(Game),Blocks(Game),Turnover(Game),id
0,1980,Kareem Abdul-Jabbar,C,38.3,24.8,4.5,10.8,1.0,3.4,3.6,0
1,1980,Tom Abernethy,PF,18.2,5.4,1.3,2.9,0.5,0.2,0.6,1
2,1980,Alvan Adams,C,28.9,14.9,4.3,8.1,1.4,0.7,2.9,2
3,1980,Tiny Archibald,PG,35.8,14.1,8.4,2.5,1.3,0.1,3.0,3
4,1980,Dennis Awtrey,C,21.5,3.3,1.5,4.4,0.5,0.6,1.0,4
...,...,...,...,...,...,...,...,...,...,...,...
18922,2017,Cody Zeller,PF,27.8,10.3,1.6,6.5,1.0,0.9,1.0,18922
18923,2017,Tyler Zeller,C,10.3,3.5,0.8,2.4,0.1,0.4,0.4,18923
18924,2017,Stephen Zimmerman,C,5.7,1.2,0.2,1.8,0.1,0.3,0.2,18924
18925,2017,Paul Zipser,SF,19.2,5.5,0.8,2.8,0.3,0.4,0.9,18925
18926,2017,Ivica Zubac,C,16.0,7.5,0.8,4.2,0.4,0.9,0.8,18926

In [35]:
master_first_df = pd.merge(seasons_df, players_df, how="left", on=["Player"])
master_first_df

,Year,Player,Position,Age,Team,G,GS,MP,PER,TS%,...,PF,PTS,id,AllStar,height,weight,born,year_start,year_end,position
0,1980.0,Kareem Abdul-Jabbar,C,32,LAL,82,0,3143,25.3,0.639,...,216.0,2034,0,1,86,225,1947,NaN,NaN,None
1,1980.0,Tom Abernethy,PF,25,GSW,67,0,1222,11.0,0.511,...,118.0,362,1,0,79,218,1954,NaN,NaN,None
2,1980.0,Alvan Adams,C,25,PHO,75,0,2168,19.2,0.571,...,237.0,1118,2,0,81,209,1954,NaN,NaN,None
3,1980.0,Tiny Archibald,PG,31,BOS,80,80,2864,15.3,0.574,...,218.0,1131,3,1,73,150,1948,NaN,NaN,None
4,1980.0,Dennis Awtrey,C,31,CHI,26,0,560,7.4,0.524,...,66.0,86,4,0,82,234,1948,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,2017.0,Cody Zeller,PF,24,CHO,62,58,1725,16.7,0.604,...,189.0,639,18922,0,84,238,1992,2014.0,2018.0,C
18923,2017.0,Tyler Zeller,C,27,BOS,51,5,525,13.0,0.508,...,61.0,178,18923,0,84,251,1990,2013.0,2018.0,F
18924,2017.0,Stephen Zimmerman,C,20,ORL,19,0,108,7.3,0.346,...,17.0,23,18924,0,84,238,1996,2017.0,2017.0,C
18925,2017.0,Paul Zipser,SF,22,CHI,44,18,843,6.9,0.503,...,78.0,240,18925,0,80,214,1994,2017.0,2018.0,G
18926,2017.0,Ivica Zubac,C,19,LAL,38,11,609,17.0,0.547,...,66.0,284,18926,0,85,265,1997,2017.0,2018.0,C

In [36]:
master_final_df = pd.merge(master_first_df, per_game_df, how="left", on=["id"])
master_final_df

,Year_x,Player_x,Position,Age,Team,G,GS,MP,PER,TS%,...,Year_y,Player_y,Pos,MP(Game),Points(Game),Assists(Game),Rebounds(Game),Steals(Game),Blocks(Game),Turnover(Game)
0,1980.0,Kareem Abdul-Jabbar,C,32,LAL,82,0,3143,25.3,0.639,...,1980,Kareem Abdul-Jabbar,C,38.3,24.8,4.5,10.8,1.0,3.4,3.6
1,1980.0,Tom Abernethy,PF,25,GSW,67,0,1222,11.0,0.511,...,1980,Tom Abernethy,PF,18.2,5.4,1.3,2.9,0.5,0.2,0.6
2,1980.0,Alvan Adams,C,25,PHO,75,0,2168,19.2,0.571,...,1980,Alvan Adams,C,28.9,14.9,4.3,8.1,1.4,0.7,2.9
3,1980.0,Tiny Archibald,PG,31,BOS,80,80,2864,15.3,0.574,...,1980,Tiny Archibald,PG,35.8,14.1,8.4,2.5,1.3,0.1,3.0
4,1980.0,Dennis Awtrey,C,31,CHI,26,0,560,7.4,0.524,...,1980,Dennis Awtrey,C,21.5,3.3,1.5,4.4,0.5,0.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,2017.0,Cody Zeller,PF,24,CHO,62,58,1725,16.7,0.604,...,2017,Cody Zeller,PF,27.8,10.3,1.6,6.5,1.0,0.9,1.0
18923,2017.0,Tyler Zeller,C,27,BOS,51,5,525,13.0,0.508,...,2017,Tyler Zeller,C,10.3,3.5,0.8,2.4,0.1,0.4,0.4
18924,2017.0,Stephen Zimmerman,C,20,ORL,19,0,108,7.3,0.346,...,2017,Stephen Zimmerman,C,5.7,1.2,0.2,1.8,0.1,0.3,0.2
18925,2017.0,Paul Zipser,SF,22,CHI,44,18,843,6.9,0.503,...,2017,Paul Zipser,SF,19.2,5.5,0.8,2.8,0.3,0.4,0.9
18926,2017.0,Ivica Zubac,C,19,LAL,38,11,609,17.0,0.547,...,2017,Ivica Zubac,C,16.0,7.5,0.8,4.2,0.4,0.9,0.8

In [37]:
X = master_final_df.copy().drop("AllStar", axis=1)
X

,Year_x,Player_x,Position,Age,Team,G,GS,MP,PER,TS%,...,Year_y,Player_y,Pos,MP(Game),Points(Game),Assists(Game),Rebounds(Game),Steals(Game),Blocks(Game),Turnover(Game)
0,1980.0,Kareem Abdul-Jabbar,C,32,LAL,82,0,3143,25.3,0.639,...,1980,Kareem Abdul-Jabbar,C,38.3,24.8,4.5,10.8,1.0,3.4,3.6
1,1980.0,Tom Abernethy,PF,25,GSW,67,0,1222,11.0,0.511,...,1980,Tom Abernethy,PF,18.2,5.4,1.3,2.9,0.5,0.2,0.6
2,1980.0,Alvan Adams,C,25,PHO,75,0,2168,19.2,0.571,...,1980,Alvan Adams,C,28.9,14.9,4.3,8.1,1.4,0.7,2.9
3,1980.0,Tiny Archibald,PG,31,BOS,80,80,2864,15.3,0.574,...,1980,Tiny Archibald,PG,35.8,14.1,8.4,2.5,1.3,0.1,3.0
4,1980.0,Dennis Awtrey,C,31,CHI,26,0,560,7.4,0.524,...,1980,Dennis Awtrey,C,21.5,3.3,1.5,4.4,0.5,0.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,2017.0,Cody Zeller,PF,24,CHO,62,58,1725,16.7,0.604,...,2017,Cody Zeller,PF,27.8,10.3,1.6,6.5,1.0,0.9,1.0
18923,2017.0,Tyler Zeller,C,27,BOS,51,5,525,13.0,0.508,...,2017,Tyler Zeller,C,10.3,3.5,0.8,2.4,0.1,0.4,0.4
18924,2017.0,Stephen Zimmerman,C,20,ORL,19,0,108,7.3,0.346,...,2017,Stephen Zimmerman,C,5.7,1.2,0.2,1.8,0.1,0.3,0.2
18925,2017.0,Paul Zipser,SF,22,CHI,44,18,843,6.9,0.503,...,2017,Paul Zipser,SF,19.2,5.5,0.8,2.8,0.3,0.4,0.9
18926,2017.0,Ivica Zubac,C,19,LAL,38,11,609,17.0,0.547,...,2017,Ivica Zubac,C,16.0,7.5,0.8,4.2,0.4,0.9,0.8

In [38]:
y = master_final_df["AllStar"]
y

0        1
1        0
2        0
3        1
4        0
        ..
18922    0
18923    0
18924    0
18925    0
18926    0
Name: AllStar, Length: 18927, dtype: int64

In [39]:
X.columns

Index(['Year_x', 'Player_x', 'Position', 'Age', 'Team', 'G', 'GS', 'MP', 'PER',
       'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%',
       'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM',
       'VORP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%',
       'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'id', 'height', 'weight', 'born', 'year_start',
       'year_end', 'position', 'Year_y', 'Player_y', 'Pos', 'MP(Game)',
       'Points(Game)', 'Assists(Game)', 'Rebounds(Game)', 'Steals(Game)',
       'Blocks(Game)', 'Turnover(Game)'],
      dtype='object')

In [41]:
X = X.copy().drop(['Player_x','Year_x','Team','id','born', 'year_start', 'year_end', 'position', 'Year_y', 'Player_y', 'Pos'], axis=1)
X

#df.drop(['C', 'D'], axis = 1)

,Position,Age,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,...,PTS,height,weight,MP(Game),Points(Game),Assists(Game),Rebounds(Game),Steals(Game),Blocks(Game),Turnover(Game)
0,C,32,82,0,3143,25.3,0.639,0.001,0.344,7.2,...,2034,86,225,38.3,24.8,4.5,10.8,1.0,3.4,3.6
1,PF,25,67,0,1222,11.0,0.511,0.003,0.258,5.4,...,362,79,218,18.2,5.4,1.3,2.9,0.5,0.2,0.6
2,C,25,75,0,2168,19.2,0.571,0.002,0.270,8.2,...,1118,81,209,28.9,14.9,4.3,8.1,1.4,0.7,2.9
3,PG,31,80,80,2864,15.3,0.574,0.023,0.548,2.3,...,1131,73,150,35.8,14.1,8.4,2.5,1.3,0.1,3.0
4,C,31,26,0,560,7.4,0.524,0.000,0.833,6.0,...,86,82,234,21.5,3.3,1.5,4.4,0.5,0.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,PF,24,62,58,1725,16.7,0.604,0.002,0.442,8.6,...,639,84,238,27.8,10.3,1.6,6.5,1.0,0.9,1.0
18923,C,27,51,5,525,13.0,0.508,0.006,0.247,9.2,...,178,84,251,10.3,3.5,0.8,2.4,0.1,0.4,0.4
18924,C,20,19,0,108,7.3,0.346,0.000,0.161,10.8,...,23,84,238,5.7,1.2,0.2,1.8,0.1,0.3,0.2
18925,SF,22,44,18,843,6.9,0.503,0.448,0.181,1.9,...,240,80,214,19.2,5.5,0.8,2.8,0.3,0.4,0.9
18926,C,19,38,11,609,17.0,0.547,0.013,0.206,7.1,...,284,85,265,16.0,7.5,0.8,4.2,0.4,0.9,0.8

In [42]:
#X.rename(columns = {'Pos_x':'Position'}, inplace=True)
#X

#rename(columns = {'test':'TEST'}, inplace = True)

In [43]:
X = pd.get_dummies(X, columns=["Position"])
X

#X = pd.get_dummies(df_cluster, columns=["Algorithm","ProofType"])
#X

,Age,G,GS,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,...,Position_PG,Position_PG-SF,Position_PG-SG,Position_SF,Position_SF-PF,Position_SF-SG,Position_SG,Position_SG-PF,Position_SG-PG,Position_SG-SF
0,32,82,0,3143,25.3,0.639,0.001,0.344,7.2,22.2,...,0,0,0,0,0,0,0,0,0,0
1,25,67,0,1222,11.0,0.511,0.003,0.258,5.4,12.0,...,0,0,0,0,0,0,0,0,0,0
2,25,75,0,2168,19.2,0.571,0.002,0.270,8.2,22.4,...,0,0,0,0,0,0,0,0,0,0
3,31,80,80,2864,15.3,0.574,0.023,0.548,2.3,5.3,...,1,0,0,0,0,0,0,0,0,0
4,31,26,0,560,7.4,0.524,0.000,0.833,6.0,16.9,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18922,24,62,58,1725,16.7,0.604,0.002,0.442,8.6,17.3,...,0,0,0,0,0,0,0,0,0,0
18923,27,51,5,525,13.0,0.508,0.006,0.247,9.2,17.0,...,0,0,0,0,0,0,0,0,0,0
18924,20,19,0,108,7.3,0.346,0.000,0.161,10.8,24.9,...,0,0,0,0,0,0,0,0,0,0
18925,22,44,18,843,6.9,0.503,0.448,0.181,1.9,14.2,...,0,0,0,1,0,0,0,0,0,0
18926,19,38,11,609,17.0,0.547,0.013,0.206,7.1,21.9,...,0,0,0,0,0,0,0,0,0,0

In [44]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [45]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [46]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [47]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [48]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [49]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0         4456           40
Actual 1           95          141

In [50]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [51]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         4456           40
Actual 1           95          141

Accuracy Score : 0.9714708368554522
Classification Report
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4496
           1       0.78      0.60      0.68       236

    accuracy                           0.97      4732
   macro avg       0.88      0.79      0.83      4732
weighted avg       0.97      0.97      0.97      4732

In [52]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([8.88900466e-03, 7.93090313e-03, 9.38391681e-03, 1.27191798e-02,
       5.20721332e-02, 7.32277891e-03, 6.50708371e-03, 8.30975685e-03,
       6.71544749e-03, 8.99236561e-03, 7.52193082e-03, 1.05998632e-02,
       6.43803102e-03, 7.65761065e-03, 7.75864141e-03, 2.08932133e-02,
       3.86784276e-02, 2.16286941e-02, 6.19998194e-02, 2.85330310e-02,
       1.34738002e-02, 9.23300880e-03, 2.55186972e-02, 5.34641116e-02,
       3.54708553e-02, 2.37105039e-02, 8.02092061e-03, 6.48419891e-03,
       6.65248330e-03, 7.11315867e-03, 2.51709103e-02, 2.23044347e-02,
       6.70457522e-03, 6.99942774e-03, 4.68538551e-02, 3.02811350e-02,
       8.37671054e-03, 8.41469742e-03, 1.25781971e-02, 1.22824944e-02,
       1.13466021e-02, 8.06989436e-03, 9.12318493e-03, 1.45388468e-02,
       1.06765062e-02, 7.10189508e-02, 6.12903437e-03, 7.08877564e-03,
       2.64813837e-02, 7.67846965e-02, 1.16564333e-02, 9.15875727e-03,
       6.38102890e-03, 5.75882694e-03, 1.26084381e-02, 6.38537450e-04,
       0.00000000e+00, 0.00000000e+00, 6.35146428e-04, 0.00000000e+00,
       0.00000000e+00, 6.23802375e-04, 0.00000000e+00, 6.37951724e-05,
       7.83892336e-04, 0.00000000e+00, 0.00000000e+00, 6.10050945e-04,
       0.00000000e+00, 1.63406599e-04, 0.00000000e+00])

In [53]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.07678469654927311, 'Points(Game)'),
 (0.071018950809094, 'PTS'),
 (0.06199981941807298, 'WS'),
 (0.05346411159592237, 'VORP'),
 (0.05207213319109772, 'PER'),
 (0.04685385505368492, 'FT'),
 (0.03867842759558619, 'OWS'),
 (0.03547085527620601, 'FG'),
 (0.030281134996597805, 'FTA'),
 (0.028533031040035926, 'WS/48'),
 (0.02648138369093161, 'MP(Game)'),
 (0.02551869718271973, 'BPM'),
 (0.02517091030711278, '2P'),
 (0.023710503899327506, 'FGA'),
 (0.022304434693910448, '2PA'),
 (0.0216286940620339, 'DWS'),
 (0.020893213314072685, 'USG%'),
 (0.0145388468250182, 'TOV'),
 (0.013473800243785397, 'OBPM'),
 (0.012719179754811169, 'MP'),
 (0.012608438132307078, 'Turnover(Game)'),
 (0.012578197107260387, 'DRB'),
 (0.012282494419852998, 'TRB'),
 (0.011656433346214612, 'Assists(Game)'),
 (0.011346602092336682, 'AST'),
 (0.010676506215908215, 'PF'),
 (0.01059986318843948, 'AST%'),
 (0.009383916808198034, 'GS'),
 (0.009233008804799655, 'DBPM'),
 (0.009158757273437772, 'Rebounds(Game)'),
 (0.00912318493268031, 'BLK'),
 (0.008992365606497184, 'DRB%'),
 (0.008889004663405954, 'Age'),
 (0.008414697416037462, 'ORB'),
 (0.008376710540876641, 'FT%'),
 (0.008309756848054784, 'FTr'),
 (0.008069894358042607, 'STL'),
 (0.008020920609389944, 'FG%'),
 (0.007930903128840138, 'G'),
 (0.007758641407687119, 'TOV%'),
 (0.007657610645829487, 'BLK%'),
 (0.007521930816557664, 'TRB%'),
 (0.007322778911500872, 'TS%'),
 (0.007113158666132072, '3P%'),
 (0.007088775641933253, 'weight'),
 (0.0069994277398547945, 'eFG%'),
 (0.006715447494691198, 'ORB%'),
 (0.006704575224917512, '2P%'),
 (0.006652483303924717, '3PA'),
 (0.006507083710722266, '3PAr'),
 (0.006484198907530666, '3P'),
 (0.006438031024538702, 'STL%'),
 (0.00638102890406927, 'Steals(Game)'),
 (0.006129034365982542, 'height'),
 (0.005758826937450313, 'Blocks(Game)'),
 (0.0007838923357623783, 'Position_SF'),
 (0.0006385374500183218, 'Position_C'),
 (0.0006351464282309621, 'Position_PF'),
 (0.0006238023745236231, 'Position_PG'),
 (0.0006100509445573335, 'Position_SG'),
 (0.0001634065992990261, 'Position_SG-PG'),
 (6.379517241153363e-05, 'Position_PG-SG'),
 (0.0, 'Position_SG-SF'),
 (0.0, 'Position_SG-PF'),
 (0.0, 'Position_SF-SG'),
 (0.0, 'Position_SF-PF'),
 (0.0, 'Position_PG-SF'),
 (0.0, 'Position_PF-SF'),
 (0.0, 'Position_PF-C'),
 (0.0, 'Position_C-SF'),
 (0.0, 'Position_C-PF')]